### ISSUE TITLE
So... HOW is the editor supposed to be used, exactly?

### ISSUE THREAD

**Issue by Onikage056** [GrimChan/GenZ-Save-File-Editor#5]
Now, I'll admit, I'm no programmer... but, generally speaking here, programs require an executable to work. Something this save editor is missing.

**Comment by GrimChan** [comment]
This project has been dead for a while, the codebase is terrible and I don't play the game anymore. This was uploaded mostly if anybody felt like restarting the project. There isn't an executable due to this mostly just being an archive, they used to be uploaded to Nexus Mods but I removed them since the game updates broke the existing version. Wish you the best.
